### ISSUE TITLE
Unable to start nodes with subnet EVM

### ISSUE THREAD

**Issue by Nuttymoon** [ava-labs/subnet-evm#1]
Hi!

I am trying to create a blockchain using the subnet EVM but the nodes won't start after placing the VM binary in `build/plugins`. Here is the error:
```
FATAL[01-10|09:33:25] app/process/process.go#162: error initializing node: couldn't initialize chain manager: Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

I built the subnet EVM (with go1.17.3 on Ubuntu 20.04) using:
```sh
cd subnet-evm
./scripts/build.sh ./build/spePNvBxaWSYL2tB5e2xMmMNBQkXMN8z2XEbz1ML2Aahatwoc
Using branch: v0.0.2
Building Subnet EVM Version: v0.1.0; GitCommit: a59f55e17460eada644b6942895d281407120be9
```

I tried using different versions of avalanchego (1.6.0, 1.6.5, 1.7.0, 1.7.2) but the error remains. Btw I am running the Avalanche nodes using the Docker [avaplatform/avalanchego](https://hub.docker.com/r/avaplatform/avalanchego) images.

**Comment by ceyonur** [comment]
1.6.0 and 1.6.5 are not supported. versions newer than 1.7.0 works with subnet evm. 
To understand the context can you share these:
1- Can you provide details about how you run your nodes? I.e CLI flags, configs, docker startup flags.
2- Have you created/whitelisted the subnet and created the chain? Or does this occur in the first startup? 
3- Were you able to reproduce this without the docker? 
Thanks!

**Comment by Nuttymoon** [comment]
So the issue appears to be linked to Docker somehow. It might be because I use a volume to bring the VM binary to the container.

I managed to run the subnet EVM on Ubuntu VMs so I think we can close this issue. I will open a new one later with more details if needed.
