### ISSUE TITLE
Many CI jobs cannot be trivially reproduced locally

### ISSUE THREAD

**Issue by marun** [ava-labs/subnet-evm#1044]
**Describe the bug**
Currently many CI jobs (precompile, load and warp jobs) require sourcing an avalanchego binary, building subnet-evm, and then executing a given test suite against those dependencies.  This complicates CI reproduceability when updating the dependent version of avalanchego.

**Expected behavior**
The script entry points should be responsible for sourcing the avalanchego binary and building subnet-evm to simplify changing the dependent version of avalanchego.

**Comment by darioush** [comment]
Curious if an approach like this would work: https://medium.com/@debasishkumardas5/running-github-actions-locally-a-complete-guide-for-windows-mac-and-linux-users-34c45999c7cd
