### ISSUE TITLE
Failed to compile e2e:

### ISSUE THREAD

**Issue by rahul-spirit** [ava-labs/subnet-evm#117]
`./scripts/run.sh 1.7.10 0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC`  Responds with Failed to complie e2e

`main module (github.com/ava-labs/subnet-evm) does not contain package github.com/ava-labs/subnet-evm/tests/e2e`

**Comment by aaronbuchwald** [comment]
@rahul-spirit I believe this issue has been fixed.

```
./scripts/run.sh 1.7.13 0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC
```

Gives me a successful test run on master. Please re-open if you are still experiencing this issue with the latest from subnet-evm and avalanchego.
