### ISSUE TITLE
Cannnot mint native coin

### ISSUE THREAD

**Issue by bafu** [ava-labs/subnet-evm#169]
**Describe the bug**

After creating a workable subnet, the admin cannot mint native coins.

I have add `contractNativeMinterConfig` in the `genesis.json`.

**To Reproduce**

1. Create my [`genesis.json`](https://pastebin.mozilla.org/bUBq4rEg) referring to the [genesis example](https://github.com/ava-labs/subnet-evm/tree/master/contract-examples#tests).
1. Create a workable subnet following the official document: [Create an EVM Subnet on Fuji Testnet](https://docs.avax.network/subnets/create-a-fuji-subnet).
1. Create `NativeMinterInterface` following the official document: [Minting Native Coins](https://docs.avax.network/subnets/customize-a-subnet#minting-native-coins).
1. Use Hardhat console to call `mintNativeCoin`.

```
> contract = await ethers.getContractAt("NativeMinterInterface", "0x0200000000000000000000000000000000000001")

> [admin] = await ethers.getSigners()

> await admin.getBalance()
BigNumber { value: "99999999999845284000000300" }

> r = await contract.mintNativeCoin(admin.address, 100)
{
  hash: '0x87fd1435355b54bc5e7f0eb07d826df43ba043bdab1ea7c3766dac11725908d3',
  type: 0,
  accessList: null,
  blockHash: '0xd2c8176d26e1d3c8a400d3a9d15cbf0e258b35dc0a5cde91deab40d95461e709',
  blockNumber: 4,
  transactionIndex: 0,
  confirmations: 1,
  from: '0x63B7076FC0A914Af543C2e5c201df6C29FCC18c5',
  gasPrice: BigNumber { value: "1000000000" },
  gasLimit: BigNumber { value: "51572" },
  to: '0x0200000000000000000000000000000000000001',
  value: BigNumber { value: "0" },
  nonce: 3,
  data: '0x4f5aaaba00000000000000000000000063b7076fc0a914af543c2e5c201df6c29fcc18c50000000000000000000000000000000000000000000000000000000000000064',
  r: '0xa163fd7b436369e19488abfa288ff760f89cd6d519a2e0b7710bd2de9fe0683f',
  s: '0x0e175ca8e5c63709b9dbe9ebc830b141c11d808a383975effb4b017ebc09386b',
  v: 21052,
  creates: null,
  chainId: 10508,
  wait: [Function (anonymous)]
}

> await admin.getBalance()
BigNumber { value: "99999999999793712000000400" }
```

**Expected behavior**

Admin can mint native coins and receives the minted coins.

**Screenshots**

N/A

**Logs**

[Complete Hardhat logs](https://pastebin.mozilla.org/JqBigk2t)

**Metrics**

N/A

**Operating System**

1. OS: Ubuntu 20.04.4 LTS (AWS instance)
2. Avalanchego: v1.7.14
3. subnet-evm: commit 1a7f57e (2022-07-01)

**Additional context**

Shared this issue in #subnet-chat on Discord, and the team asked for more details. Please feel free to let me know what are the logs to be helpful, and I will provide them soon. Thanks!

Avalanche Bug Bounty program can be found [here](https://hackenproof.com/avalanche/avalanche-protocol).

**Comment by Julian-dev28** [comment]
Hello 

Thank you for bringing this up

Have you tried minting the uint256 value for 100?

100000000000000000000

or 

1e20

I actually see that there is a different balance from the first and last time you call getBalance leading me to believe that you may just need to use the uint256 version of the value you are trying to send

> await admin.getBalance()
BigNumber { value: "99999999999845284000000300" }
..
> await admin.getBalance()
BigNumber { value: "99999999999793712000000400" }

you can use this tool if you'd like to converter eth to gwei easily

**Comment by Julian-dev28** [comment]
```
> ethers.utils.formatUnits(await admin.getBalance()).toString()
'100000000.000844296000000001'
> await nm.mintNativeCoin(admin.address,'10000000000000000000')
{
  hash: '0x46e82b35fe85d16b54bd65baab2b1fcb218b9296c117d560d7f9e5453d48fc64',
  type: 0,
  accessList: null,
  blockHash: null,
  blockNumber: null,
  transactionIndex: null,
  confirmations: 0,
  from: '0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC',
  gasPrice: BigNumber { _hex: '0x3b9aca00', _isBigNumber: true },
  gasLimit: BigNumber { _hex: '0xc9b0', _isBigNumber: true },
  to: '0x0200000000000000000000000000000000000001',
  value: BigNumber { _hex: '0x00', _isBigNumber: true },
  nonce: 8,
  data: '0x4f5aaaba0000000000000000000000008db97c7cece249c2b98bdc0226cc4c2a57bf52fc0000000000000000000000000000000000000000000000008ac7230489e80000',
  r: '0xb488c277684bb9406b3d28b94b7ea8564c8a3214ed73025e9cd5829caae150ec',
  s: '0x450dfd556cf43a1ea2f7b069e2e18f48decaade0c6a4552f769441bbd6e40c63',
  v: 200034,
  creates: null,
  chainId: 99999,
  wait: [Function (anonymous)]
}
> ethers.utils.formatUnits(await admin.getBalance()).toString()
'100000010.000792664000000001'
```

Been running tests locally to verify. You do need to pass in the uint256 version of the value

**Comment by bafu** [comment]
@Julian-dev28 Thanks for your quick reply and suggestion!

I also double-checked that the `amount` unit in `mintNativeCoin` is Wei instead of Gwei.

```
> r = await contract.mintNativeCoin(admin.address, 17)
{
  hash: '0x102f142ff3f68725bc91a5a02f80a9ea6c8bb358764a20021fdeb00f36fe6f48',
  type: 0,
  accessList: null,
  blockHash: '0xd9f14d3eabbc92d71a483876544300ed475dd24ea19123c2f728e6d430470d41',
  blockNumber: 5,
  transactionIndex: 0,
  confirmations: 1,
  from: '0x63B7076FC0A914Af543C2e5c201df6C29FCC18c5',
  gasPrice: BigNumber { value: "1000000000" },
  gasLimit: BigNumber { value: "51572" },
  to: '0x0200000000000000000000000000000000000001',
  value: BigNumber { value: "0" },
  nonce: 4,
  data: '0x4f5aaaba00000000000000000000000063b7076fc0a914af543c2e5c201df6c29fcc18c50000000000000000000000000000000000000000000000000000000000000011',
  r: '0xc6204c4b125c4041443a0c87d8eeddfcb8e9cd5b063976a55bff2b9de9ddf3e7',
  s: '0x3bb9f194143e1ec9e7791d6b923ede1a8c34c7e3e4bc1f9151d5d16fda185854',
  v: 21052,
  creates: null,
  chainId: 10508,
  wait: [Function (anonymous)]
}
> await admin.getBalance()
BigNumber { value: "99999999999742140000000417" }
```

**Comment by Julian-dev28** [comment]
Glad to help

Feel free to reach out if you have anymore questions
