### ISSUE TITLE
`cannot parse invalid wire-format data` GRPC error seen in some E2E executions

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/subnet-evm#171]
**Describe the bug**
Error `grpc: failed to unmarshal the received message proto:\u00a0cannot parse invalid wire-format data` in seen in some E2E executions. This is related to ANR GRPC usage under runner.StartNetwork().
eg https://github.com/ava-labs/subnet-evm/runs/7544641585?check_suite_focus=true

**To Reproduce**
Execute E2E under `b69c71e49a8bdcd6aaee64a052bb3d01913e1eeb`
`E2E=true scripts/run.sh 1.7.13 0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC`

**Expected behavior**
E2E failure (probably flaky) with the given err msg

**Screenshots**

**Logs**
stdout/stderr of E2E

**Metrics**

**Operating System**
ubuntu

**Additional context**

Avalanche Bug Bounty program can be found [here](https://hackenproof.com/avalanche/avalanche-protocol).

**Comment by aaronbuchwald** [comment]
@felipemadero should this issue be moved to the avalanche-network-runner since the error is coming from starting the network or is there a reason to think that the issue here is coming from how it's used by the subnet-evm e2e tests?

**Comment by felipemadero** [comment]
> @felipemadero should this issue be moved to the avalanche-network-runner since the error is coming from starting the network or is there a reason to think that the issue here is coming from how it's used by the subnet-evm e2e tests?

@aaronbuchwald the answer seems to be yes for both questions, but we surely can move this to ANR, because it should give a more stable API
