### ISSUE TITLE
decide on canonical name for subnet-evm

### ISSUE THREAD

**Issue by ceyonur** [ava-labs/subnet-evm#179]
Currently many names can be used for subnet-evm. Let's decide on one and start using it as case sensitive. Some alternatives:
* `subnet-evm`
* `Subnet-EVM`
* `Subnet EVM`
* `SubnetEVM`
* `subnet-EVM`
* `subnet EVM` 

We should change README in subnet-evm repo, documentation site and other places accordingly.

**Comment by ceyonur** [comment]
My opinions:
1- we should not use lowercase for subnet and uppercase for EVM. I.e `subnet-EVM` or `subnet EVM` etc. They should both start uppercase or lowercase at the same time.
2- We should not use `SubnetEVM`, `subnetevm`, `subnetEVM` variants, since then the repo name does not align. Otherwise we could have just named the repo `subnetevm`.

**Comment by dasconnor** [comment]
My recommendation would be the name is `subnet-evm`; however, when in title case, it should be `Subnet-EVM`.

**Comment by aaronbuchwald** [comment]
Ok, let's go with subnet-evm in that case.
