### ISSUE TITLE
Add log print-out for network upgrade

### ISSUE THREAD

**Issue by yulin-dong** [ava-labs/subnet-evm#199]
During the WAGMI network upgrade, it was noticed that there was no log print-out on the timestamp of network upgrade. It would be helpful to print a message right after the timestamp to indicate an upgrade just happened and other related info.

**Comment by aaronbuchwald** [comment]
We should emit this log during Accept by using the changes from this PR: https://github.com/ava-labs/coreth-internal/pull/993 so that we can check what precompiles are activated when the block is accepted and emit a log if any new ones are present.
