### ISSUE TITLE
Add WAGMI Upgrade Bytes

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/subnet-evm#202]
We should add the WAGMI upgrade bytes to: https://github.com/ava-labs/subnet-evm/tree/master/networks/11111

**Comment by patrick-ogrady** [comment]
Should just be: https://gist.github.com/aaronbuchwald/b3af9da34678f542ce31717e7963085b

**Comment by aaronbuchwald** [comment]
Closed by #208
