### ISSUE TITLE
Allow feeRecepient address to be updated

### ISSUE THREAD

**Issue by darioush** [ava-labs/subnet-evm#235]
**Context and scope**
Make the fee recipient address updatable after genesis 

**Discussion and alternatives**
Could be done as a precomile contract upgrade with an Allowlist or each update could be a network upgrade. 

**Open questions**
...

**Comment by aaronbuchwald** [comment]
Added a design to an issue created here as well: https://github.com/ava-labs/subnet-evm/issues/174

**Comment by aaronbuchwald** [comment]
Closing in favor of #174
