### ISSUE TITLE
./script/run.sh dont work

### ISSUE THREAD

**Issue by riontric** [ava-labs/subnet-evm#251]
./script/run.sh don't work.
Closing error:
![image](https://user-images.githubusercontent.com/91901335/188440617-1c9b2589-6e5c-4187-b5a9-a72f19084265.png)

**Comment by aaronbuchwald** [comment]
@gyuho could you take a look at this issue when you get a chance?

**Comment by gyuho** [comment]
This should be fixed by https://github.com/ava-labs/subnet-evm/pull/238
