### ISSUE TITLE
Add test for goreleaser into CI

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#299]
We should add a better test for the goreleaser to ensure that our release pipeline fails early instead of on release.

We recently had a case where goreleaser failed to build which was fixed in this commit: https://github.com/ava-labs/subnet-evm/commit/b1d13516dde50431b10f98cc520470404ef0a959.

We should add a unit test to catch that we are breaking goreleaser, so that we will see these potential issues earlier in development.

**Comment by ceyonur** [comment]
Any update on this?
