### ISSUE TITLE
Update goreleaser to install osx cross in a different directory and remove the nested subnet-evm subdirectory

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#300]
This ticket is to modify the goreleaser file to avoid needing to created a nested subdirectory for subnet-evm in order to ensure that the git state is unmodified when building the release.

Adding the OSX Cross SDK created an initial failure when building the v0.4.0 release due to the fact that the OSX cross SDK was installed into the same directory, such that goreleaser recognized this as an error and refused to build the release.

We should modify the goreleaser file to download the OSX Cross SDK directly into the bin directory instead of the working directory, so that it can be used without changing the git state of the working subnet-evm directory.

Then we should be able to remove the nesting added to the release github action.

**Comment by ceyonur** [comment]
Any update on this?

**Comment by aaronbuchwald** [comment]
Closing in favor of a new ticket to remove this dependency completely: https://github.com/ava-labs/subnet-evm/issues/503
