### ISSUE TITLE
AVAX Subnet vs Subnet-EVM

### ISSUE THREAD

**Issue by CryptoDevving** [ava-labs/subnet-evm#309]
Is this just a testnet framework or can we launch this as a public chain without staking AVAX?

If so how can I make it public facing?

**Comment by aaronbuchwald** [comment]
Subnet-EVM implements the virtual machine interface for AvalancheGo, so that it can be used to launch EVM Chains on Avalanche Subnets.

All of the EVM Chains on the Avalanche Subnet explorer (except for the C-Chain which uses Coreth) use subnet-evm so it is used in both production and on testnets.

**Comment by CryptoDevving** [comment]
So would I still have to stake 2000 AVAX to use this as a main net?

**Comment by aaronbuchwald** [comment]
Yes, to deploy Subnet-EVM on Avalanche Mainnet each validator for that subnet would be required to stake 2,000 AVAX.

**Comment by aaronbuchwald** [comment]
Closing this ticket, since this question has been answered. Feel free to re-open if you have any further questions on this or feel free to reach out in our Discord if you have questions like this that are not really specific to Subnet-EVM.

https://discord.com/invite/RwXY7P6
