### ISSUE TITLE
Checksum mismatch occurred while building project.

### ISSUE THREAD

**Issue by scalalang2** [ava-labs/subnet-evm#321]
**Describe the bug**
Hi,
I found a build error when I execute `go build` commands with `subnet-evm v0.4.0`

```shell
env GO111MODULE=on go build -v -o ./bin ./...
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/prometheus/client_golang v1.13.0
go: downloading github.com/ava-labs/subnet-evm v0.4.0
go: downloading github.com/ethereum/go-ethereum v1.10.[25](https://gitlab.nexon.com/projecta/platform/backend/eastsea/bc-backend/-/jobs/879486#L25)
go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
go: downloading go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.[32](https://gitlab.nexon.com/projecta/platform/backend/eastsea/bc-backend/-/jobs/879486#L32).0
go: downloading go.opentelemetry.io/otel v1.7.0
verifying github.com/ava-labs/subnet-evm@v0.4.0: checksum mismatch
	downloaded: h1:o/SuSEE6/gWQUpk8xoBH3xrU9lZd7TboMDFub2eVTgM=
	go.sum:     h1:Qhsa5s76RBWSfQkdIwQjP2532UGXMgtIp4JfH1jsS38=
```

I've tried serveral guides from [stackoverflow](https://stackoverflow.com/questions/54133789/go-modules-checksum-mismatch) but nothing changes.

**How To Reproduce**
It happens when I use WSL(Window Subsystem Linux) environment.
1. run `go mod tidy` on Window 10.
2. try `go build` on WSL

**Comment by aaronbuchwald** [comment]
This is caused by an issue with goreleaser during the subnet-evm@v0.4.0 release. Please use subnet-evm@v0.4.1: https://github.com/ava-labs/subnet-evm/releases/v0.4.1 along with AvalancheGo v1.9.1: https://github.com/ava-labs/avalanchego/releases/v1.9.1.
