### ISSUE TITLE
Precompile Contract Improvements

### ISSUE THREAD

**Issue by ceyonur** [ava-labs/subnet-evm#333]
Currently stateful precompile package suffers several issues

* Circular Import Hell with `params` package
* instead of using `getByKey` we can try to use addresses to fetch precompile configurations
* each precompile contract should have their own package with specific unit tests. Currently all precompile unit tests are in the same file
* we should reduce places where we need to put precompile key (indicated by `"ADD YOUR PRECOMPILE HERE") in the codebase.

**Comment by 0xJohnnyGault** [comment]
Caddy has a nice plugin architecture they use that would be a great model for precompiles to follow, if you need some inspiration.

https://caddyserver.com/docs/extending-caddy
