### ISSUE TITLE
Wait for Prefetch Completion

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/subnet-evm#342]
https://github.com/ava-labs/subnet-evm/pull/331

We should wait for prefetching of a desired trie to complete instead of aborting it. In the optimal case, we first process storage tries that are ready to roll instead of proceeding randomly.

**Comment by aaronbuchwald** [comment]
@patrick-ogrady should this ticket be closed since the corresponding PR was closed as well?
