### ISSUE TITLE
Add "Manager" Role to AllowList

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/subnet-evm#345]
Add a role to the AllowList precompile that enables someone to add/remove addresses from the AllowList but not affect Admins.

This is more compatible with a hot("manager")/cold("admin") setup most partners use.

**Comment by aaronbuchwald** [comment]
We should also update the existing precompiles to emit events when updates are made.

**Comment by ceyonur** [comment]
I checked this one seems that it's fairly easy to change the code, but it requires a mandatory upgrade (without a precompile upgrade) if we expand the current allow list. it's probably best to wait for a avalanachego mandatory upgrade + RPC chain protocol change (both at the same time) to put this into the code if we want this to be a mandatory upgrade.

We can also add a upgradable precompile activation and check in the allow list if manager role is activated. `PrecompileAccessibleState` provides a `BlockContext` so we can check the current timestamp from `BlockContext` and `ChainConfig` to figure out if manager allow list is enabled. If not enabled, any call to manager functions will return an error.

**Comment by aaronbuchwald** [comment]
That's a great idea to add this as a network upgrade to subnet-evm as opposed to one by one for each precompile by itself.

If we're going to do it that way, then we should try to include this in the next AvalancheGo network upgrade.

**Comment by richardpringle** [comment]
@patrick-ogrady, could we get a little more context around the problem. I get the hot vs cold and I'm thinking adding an "Owner" role makes more sense
```
0 => no-role
1 => enabled (read perms)
2 => admin (read-write)
3 => owner (admin, but can only be removed by another owner)
```
otherwise, the `manager` role would get the 3 in order to maintain backward compatibility which would be kind of weird.

But if we can get a little more context on what exactly we want to design for when it comes to hot/cold usage, maybe we could make sure that this is going to be a little more extensible in the future.

**Comment by richardpringle** [comment]
> I checked this one seems that it's fairly easy to change the code, but it requires a mandatory upgrade (without a precompile upgrade) if we expand the current allow list. it's probably best to wait for a avalanachego mandatory upgrade + RPC chain protocol change (both at the same time) to put this into the code if we want this to be a mandatory upgrade.
> 
> We can also add a upgradable precompile activation and check in the allow list if manager role is activated. `PrecompileAccessibleState` provides a `BlockContext` so we can check the current timestamp from `BlockContext` and `ChainConfig` to figure out if manager allow list is enabled. If not enabled, any call to manager functions will return an error.

@ceyonur, could I bug you for some permalinks to places in the code where we would have to incorporate the whole upgrade path? The precompile logic is simple, but I'm less familiar with how the upgrade would be activated.
