### ISSUE TITLE
Update goreleaser github action to not mark "rc"s as latest release

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#407]
This ticket is to modify the goreleaser github action to ensure that if a new tag is created with "rc" in the name, it will not be tagged as the latest release automatically.

**Comment by ceyonur** [comment]
Any update on this?

**Comment by aaronbuchwald** [comment]
This is in the backlog, I haven't looked into it yet.

**Comment by aaronbuchwald** [comment]
Fixed by #521
