### ISSUE TITLE
Add Polling to get Chainlink Oracle Prices over VM2VM messaging

### ISSUE THREAD

**Issue by anusha-ctrl** [ava-labs/subnet-evm#412]
**Context and scope**

- Add Polling to get Chainlink Oracle Prices over VM2VM messaging
- All items are actually stored by roundID: https://snowtrace.io/address/0x3CA13391E9fb38a75330fb28f8cc2eB3D9ceceED#readContract

Something to consider is how to abstractly design the polling to allow for multiple polls.

**Comment by ceyonur** [comment]
Is this blocked on Warp or any other component? Or is this still in design? Can we update labels accordingly?

**Comment by aaronbuchwald** [comment]
This is blocked on warp messaging.

Closing this since we will probably not be the team that implements this.
