### ISSUE TITLE
Update golangci-lint GitHub action to the latest

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#431]
https://golangci-lint.run/

**Comment by aaronbuchwald** [comment]
We locked in v1.47 instead of using latest to avoid issues where new releases of the linter could cause new issues in CI, but we may need to update now to fix some bugs in the GitHub action that have likely been fixed.

golint failing on a release: https://github.com/ava-labs/subnet-evm/actions/runs/3897232377/jobs/6654684688
potentially relevant issue: https://github.com/actions/setup-node/issues/332

**Comment by ceyonur** [comment]
Starting from 1.48 golangci uses go 1.19. I think we need to bump to go 1.19 in order to use it.
