### ISSUE TITLE
Avalanche Warp Messaging

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#440]
# Documentation

https://github.com/ava-labs/subnet-evm/blob/warp-e2e/precompile/contracts/warp/README.md

# Tasks

- #444
- #445
- #446
- #442
- #443
- #447
- #471
- #448
- #449
- #698

**Comment by michaelkaplan13** [comment]
Calling out a dev dependency: We'll need the precompile solidity interface in order to filter for messages to be inserted into the messages database. 

May want to consider moving the precompile solidity interface up to the top.

**Comment by aaronbuchwald** [comment]
> Calling out a dev dependency: We'll need the precompile solidity interface in order to filter for messages to be inserted into the messages database.
> 
> May want to consider moving the precompile solidity interface up to the top.

The messages database in the first ticket should be the database of messages the validator is willing to sign, so there won't be a need to filter that as any message emitted by the precompile should go in.

Any message emitted by the Warp precompile, should be added to the database when it gets accepted, so it should just need the following interface:

```
type WarpBackend interface {
	AddMessage(ctx context.Context, unsignedMessage *teleporter.UnsignedMessage) error
	GetSignature(ctx context.Context, messageHash ids.ID) ([]byte, error)
}
```

**Comment by aaronbuchwald** [comment]
@minghinmatthewlam to add a separate ticket to clean up the warp messages database and add to this ticket.

**Comment by minghinmatthewlam** [comment]
Added #471 into list of issues
