### ISSUE TITLE
Pre-post precompile interface changes including VerifyWithContext + BuildWithContext placement

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#442]
- [x] Add predicate and onAccept functions to the precompile interface
- [x] Add the ability to get the original ordering of the storage slots for a given precompile address in the access list
- [x] Change the onAccept function signature to take in all of the log data as individual arguments
- [x] Add VerifyWithContext, BuildWithContext, and ShouldVerifyWithContext to VM

**Comment by aaronbuchwald** [comment]
Addressed by #524

**Comment by meeshavax** [comment]
Think this can be closed?

**Comment by aaronbuchwald** [comment]
Yes, thanks for the bump :raised_hands:
