### ISSUE TITLE
Deprecation-Warning when building on MacOS Ventura (notify-library), PR attached

### ISSUE THREAD

**Issue by itinance** [ava-labs/subnet-evm#466]
With MacOS Ventura, a deprecation warning appears when building with [github.com/rjeczalik/notify.git](https://github.com/rjeczalik/notify/issues/216) 0.9.2

0.9.3 already contains the fix for that.  I am going to submit PR as well.

Description: https://github.com/rjeczalik/notify/issues/212

**Comment by darioush** [comment]
Linking relevant issue: https://github.com/ethereum/go-ethereum/issues/26168

**Comment by darioush** [comment]
This issue is resolved as we no longer depend on https://github.com/rjeczalik/notify (after we bumped the go-ethereum dependency we are using github.com/fsnotify/fsnotify)
