### ISSUE TITLE
Warp backend database pruning

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/subnet-evm#471]
The warp backend has a database that saves the `UnsignedMessage` upon `AddMessage` calls, mostly to address case when node gets restarted and changes its bls key. Follow up from [warp backend](https://github.com/ava-labs/subnet-evm/pull/452#issuecomment-1408714882) is to have a periodic cleanup of database messages. 

Solutions:
- Two indices database of message hash and prefix timestamp https://github.com/ava-labs/subnet-evm/pull/452#issuecomment-1407081652
- Generational pruning with two tables, "new" vs "old" tables that get migrated over. https://github.com/ava-labs/subnet-evm/pull/452#issuecomment-1409041590

**Comment by morrisettjohn** [comment]
Hi all,

The current approach that Aaron and I took is to have a configurable cap on the maximum number of entries in the database.  When the database has reached the cap, it will delete the oldest entry to make room for the new one.  Therefore, there will be two logically separated databases keeping track of entries.

The current database, where messageID -> unsignedmessage
The new database, where,     messageCount -> messageID.

This keeps the implementation simple.  And, with a large enough cap, the only messages that would be flushed out are no longer relevant to the current state.

**Comment by aaronbuchwald** [comment]
Closed by #702
