### ISSUE TITLE
Can't get AvalancheGo to load built binary

### ISSUE THREAD

**Issue by leopaul36** [ava-labs/subnet-evm#570]
**Describe the bug**

**To Reproduce**
```bash
git clone git@github.com:ava-labs/subnet-evm.git
git checkout v0.4.10
./scripts/build.sh ./build/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy
scp build/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy root@mynode:/avalanchego/current/plugins/
(avalanche go restart)
```

**Expected behavior**
AvalancheGo to load my VM without issues.

**Logs**
I can see the following log in AvalancheGo:

```
main.log:[03-13|18:06:04.275] ERROR node/node.go:827 failed to register VM {"vmID": "srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy", "error": "handshake failed: vm process not found"}
```

**Operating System**
Ubuntu 20.04

**Additional context**
Running:
- My node is running AvalancheGo 1.9.9
- Building the Subnet-EVM binary with `go version go1.19.6 linux/amd64`

If I install the binary from release https://github.com/ava-labs/subnet-evm/releases/tag/v0.4.10, I don't have the issue.

I noticed my binary is 30629960 bytes and the release's binary is 30117360 bytes there's a difference in what's being built.

Also tried with v0.4.9 but had the same issue.

**Comment by aaronbuchwald** [comment]
You can find the compatibility between AvalancheGo versions and Subnet-EVM in the Subnet-EVM README here: https://github.com/ava-labs/subnet-evm/blob/master/README.md#avalanchego-compatibility.

AvalancheGo talks to VM plugin binaries over a gRPC wrapper of the Virtual Machine interface. Each time there is any change to this interface, we bump the ProtocolVersion to ensure that a VM plugin binary and AvalancheGo binary that are using an out of date interface do not mistakenly communicate with each other.

However, AvalancheGo v1.9.9 and Subnet-EVM v0.4.9 should be compatible with each other as documented in the README. You can also see here that v0.4.9 of Subnet-EVM imports AvalancheGo v1.9.9, which means they should be compatible. Are you sure that you were running these two versions together?
I would recommend bumping to the latest version of both AvalancheGo (https://github.com/ava-labs/avalanchego/releases/tag/v1.9.11) and Subnet-EVM (https://github.com/ava-labs/subnet-evm/releases/tag/v0.4.12).

**Comment by leopaul36** [comment]
> You can find the compatibility between AvalancheGo versions and Subnet-EVM in the Subnet-EVM README here: https://github.com/ava-labs/subnet-evm/blob/master/README.md#avalanchego-compatibility.
> 
> AvalancheGo talks to VM plugin binaries over a gRPC wrapper of the Virtual Machine interface. Each time there is any change to this interface, we bump the ProtocolVersion to ensure that a VM plugin binary and AvalancheGo binary that are using an out of date interface do not mistakenly communicate with each other.
> 
> However, AvalancheGo v1.9.9 and Subnet-EVM v0.4.9 should be compatible with each other as documented in the README. You can also see here that v0.4.9 of Subnet-EVM imports AvalancheGo v1.9.9, which means they should be compatible. Are you sure that you were running these two versions together?
> 
> Either way, I would recommend bumping to the latest version of both AvalancheGo (https://github.com/ava-labs/avalanchego/releases/tag/v1.9.11) and Subnet-EVM (https://github.com/ava-labs/subnet-evm/releases/tag/v0.4.12).

Hi @aaronbuchwald,

I just tried with Avalanche Go 1.9.11 and Subnet-EVM v0.4.12 and I get the same behavior...

Again, trying to load the binary **I built** with `go version go1.19.6` from tag [`v0.4.12`](https://github.com/ava-labs/subnet-evm/tree/v0.4.12) **without any code modification** with `./scripts/build.sh ./build/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy` fails with this error:

```
main.log:[03-13|22:17:22.311] ERROR node/node.go:835 failed to register VM {"vmID": "srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy", "error": "handshake failed: vm process not found"}
```

If I replace my binary with the one provided in the `subnet-evm_0.4.12_linux_amd64.tar.gz` file of the [v0.4.12 assets](https://github.com/ava-labs/subnet-evm/releases/tag/v0.4.12), AvalancheGo is booting fine.

Is there anything I'm missing in the binary build?

**Comment by aaronbuchwald** [comment]
Ah this is the issue, you need to place the binary in the location that AvalancheGo expects it.

The default plugin directory is now `~/.avalanchego/plugins` so if you are running AvalancheGo with no flags or node config, then you should place the Subnet-EVM binary in `~/.avalanchego/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy`. It looks like you are building the binary but placing it into the `build/` directory within Subnet-EVM, which AvalancheGo does not know about.

Could you share the command you're using to run AvalancheGo and any config that you are using if you are still running into any issues after placing the binary in the location expected by AvalancheGo.

**Comment by leopaul36** [comment]
> Ah this is the issue, you need to place the binary in the location that AvalancheGo expects it.
> 
> The default plugin directory is now `~/.avalanchego/plugins` so if you are running AvalancheGo with no flags or node config, then you should place the Subnet-EVM binary in `~/.avalanchego/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy`. It looks like you are building the binary but placing it into the `build/` directory within Subnet-EVM, which AvalancheGo does not know about.
> 
> Could you share the command you're using to run AvalancheGo and any config that you are using if you are still running into any issues after placing the binary in the location expected by AvalancheGo.

I'm not sure the issue is about the location because the Subnet-EVM binary is loading if I only replace my built binary with the one from the release assets without changing anything else.

I am running AvalancheGo with:

```
/opt/avalanche/avalanchego/current/avalanchego --plugin-dir=/opt/avalanche/avalanchego/current/plugins --config-file=/etc/avalanche/avalanchego/conf/node.json
```

With `/etc/avalanche/avalanchego/conf/node.json`:

```
{
  "api-admin-enabled": true,
  "api-keystore-enabled": true,
  "bootstrap-ids": "",
  "bootstrap-ips": "",
  "chain-config-dir": "/etc/avalanche/avalanchego/conf/chains",
  "db-dir": "/var/lib/avalanchego/db",
  "http-host": "192.168.60.11",
  "http-port": 9650,
  "log-dir": "/var/log/avalanche/avalanchego",
  "log-level": "info",
  "network-id": "local",
  "public-ip": "192.168.60.11",
  "snow-mixed-query-num-push-vdr": 2,
  "snow-quorum-size": 2,
  "snow-sample-size": 3,
  "staking-enabled": true,
  "staking-port": 9651,
  "staking-tls-cert-file": "/etc/avalanche/avalanchego/staking/staker.crt",
  "staking-tls-key-file": "/etc/avalanche/avalanchego/staking/staker.key",
  "subnet-config-dir": "/etc/avalanche/avalanchego/conf/subnets",
  "track-subnets": ""
}
```

**Comment by leopaul36** [comment]
I think i figured out my issue. I was building the Subnet-EVM with Ubuntu 22.04 and tried to install it in a Ubuntu 20.04 VM... After switching to a Ubuntu 22.04 VM, the built binary is correctly loaded.

Would you have any tips on how to make cross-os compatible binaries?

**Comment by aaronbuchwald** [comment]
If you are running with this flag: `--plugin-dir=/opt/avalanche/avalanchego/current/plugins` then it will only look for binaries in that location. You should confirm that the binary is present in that directory. For example, you can run:

```bash
/opt/avalanche/avalanchego/current/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy --version
```

which will show you the version of the Subnet-EVM binary that will be loaded when running AvalancheGo with that `--plugin-dir` flag.

For cross compiling, Golang has great cross-compilation support. I'd suggest checking out this article to get started: https://golangcookbook.com/chapters/running/cross-compiling/

**Comment by leopaul36** [comment]
> If you are running with this flag: `--plugin-dir=/opt/avalanche/avalanchego/current/plugins` then it will only look for binaries in that location. You should confirm that the binary is present in that directory. For example, you can run:
> 
> ```shell
> /opt/avalanche/avalanchego/current/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy --version
> ```
> 
> which will show you the version of the Subnet-EVM binary that will be loaded when running AvalancheGo with that `--plugin-dir` flag.
> 
> For cross compiling, Golang has great cross-compilation support. I'd suggest checking out this article to get started: https://golangcookbook.com/chapters/running/cross-compiling/

Will try with this, thanks for your help @aaronbuchwald
