### ISSUE TITLE
Investigate Websocket abnormal closure

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/subnet-evm#592]
For the teleporter we have relayers that subscribe to nodes on a subnet to get notified when a new log event gets added from the warp precompile address. We've been noticing consistent web socket abnormal closure errors returned from the subscriber's error channel.

To compare, we hardcoded the relayer to subscribe to public websocket [endpoints](https://docs.avax.network/apis/avalanchego/public-api-server#websocket), and only noticed one occurrence of the same error after running in the background for an extended time. 

This could imply the higher error occurrence is from the setup of the local network and difference in configs.
[slack thread](https://avalancheavax.slack.com/archives/C03KRTYEMJ9/p1679612735710409)

To reproduce with Docker:
- Clone teleporter
- `git submodule sync`
- `git submodule update --init --recursive`
- Run `run.sh` which should spin up relayers and local network
- Let the network run in the background and should see abnormal closure errors from relayers

To reproduce locally: 
- Clone teleporter
- `git submodule sync`
- `git submodule update --init --recursive`
- Run `./docker/run_setup.sh --local-tests-only` to start up the two subnets
  - For `install: cannot remove '/usr/local/bin/avalanche': Permission denied` can remove the curl request to install `avalanche-cli` in the `run_setup` script
  - If run into `/teleporter/contracts/cache/solidity-files-cache.json": Permission denied (os error 13)`, give permissions `chmod +w ./solidity-files-cache.json`
  - If run into `panic: open UniversalTeleporterDeployerTransaction.txt: permission denied` run `sudo chown <user>:admin UniversalTeleporter*.txt`
- On second terminal `export SOURCE_SUBNET=subneta` and run `./docker/run_relayer.sh --local-tests-only`
- On third terminal `export SOURCE_SUBNET=subnetb` and run `./docker/run_relayer.sh --local-tests-only`
- Let it run for awhile, and should see abnormal closure error on the relayer terminals.

OS Version:
Ubuntu 20.04.6 LTS

Error returned from subscriber: `received error from subscribed node err websocket: close 1006 (abnormal closure): unexpected EOF`

**Comment by aaronbuchwald** [comment]
Closing since @minghinmatthewlam reported internally that this is no longer an issue.
