### ISSUE TITLE
Dfk stake sync: TriesRemaining stuck

### ISSUE THREAD

**Issue by crabmanpokt** [ava-labs/subnet-evm#594]
INFO [03-24|17:31:00.384] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=108h53m
INFO [03-24|17:32:00.829] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=108h28m
INFO [03-24|17:33:01.461] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=111h59m
INFO [03-24|17:34:02.136] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=113h39m
INFO [03-24|17:35:02.232] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=115h24m
INFO [03-24|17:36:02.316] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=108h52m
INFO [03-24|17:37:02.481] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=109h57m
INFO [03-24|17:38:02.656] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=112h55m
INFO [03-24|17:39:02.814] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=108h40m
INFO [03-24|17:40:03.204] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=112h39m
INFO [03-24|17:41:03.658] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=115h58m
INFO [03-24|17:42:03.709] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=111h30m
INFO [03-24|17:43:03.915] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=112h14m
INFO [03-24|17:44:03.943] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=112h20m
INFO [03-24|17:45:04.169] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=110h14m
INFO [03-24|17:46:04.755] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/sync/statesync/trie_sync_stats.go:135: state sync: syncing storage tries triesRemaining=244 ETA=110h37m

Won't go below 244. 
This is avax [v1.9.15], Subnet v0.4.12

**Comment by aaronbuchwald** [comment]
Could you provide specs of the machine that you're running on and the metrics output from your node?

Here's the docs for retrieving the metrics: https://docs.avax.network/apis/avalanchego/apis/metrics

**Comment by darioush** [comment]
This issue has been fixed in https://github.com/ava-labs/subnet-evm/pull/611
