### ISSUE TITLE
Make versions.sh and dependent scripts use consistent variable names

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/subnet-evm#597]
**Context and scope**
At some point, there was a difference between what could be defined through an environment variable and what variables were used by dependent scripts. This was originally done with lowercase variables populated by defaults or upper-case user-defined environment variables. Now, we are kind of in-between this style with all uppercase variables, but with user-defined variables having a slightly different name which makes everything confusing. 

To clean this up, we want to allow users (the script runner) to define inputs using the same names that are in the scripts.

**Discussion and alternatives**
Alternatively, we could go back to lowercase variables that aren't user-defined. 

**Open questions**
None for now

**Comment by ceyonur** [comment]
I think this was already fixed with https://github.com/ava-labs/subnet-evm/pull/989. If there are any remaining ones, we can reopen this issue.
