### ISSUE TITLE
DFK Subnet Latency on Trace Transactions

### ISSUE THREAD

**Issue by gbartolome-avax** [ava-labs/subnet-evm#603]
**Describe the bug**
We have multiple workers using new header subscriptions for the DFK subnet via websockets in our data-development environment. We are seeing errors quite frequently when new blocks at the tip are calling the debug_traceTransaction method in geth for internal transactions.

**To Reproduce**
Test locally: 

1. clone [producer](https://github.com/ava-labs/avalanche-data-producer)
2. This will need a valid DFK endpoint to reproduce 
3. go into the producer directory and run

- `make up` this builds all the Docker services locally to run the application (Kafka and Redis)
- `make run-binary` this builds the go binary and runs the producer app with the correct arguments for the DFK subnet

**Expected behavior**
Based on the Screenshots you can see that the call is not able to get the debug trace data for that transaction.

The error is pretty intermittent now that the infra team has bumped up our resources for the nodes that power that endpoint though it still happens once in a while

**Screenshots**

<img width="1572" alt="Screenshot 2023-03-27 at 9 31 33 AM" src="https://user-images.githubusercontent.com/120395684/229811457-b1626189-a50d-4be7-8674-284e04468e96.png">

**Logs**
[block_error_dfk (1).csv](https://github.com/ava-labs/subnet-evm/files/11149138/block_error_dfk.1.csv)
[trace_error_dfk (1).csv](https://github.com/ava-labs/subnet-evm/files/11149140/trace_error_dfk.1.csv)

**Metrics**
N/A

**Operating System**
Mac and AWS EKS

**Additional context**

Avalanche Bug Bounty program can be found [here](https://hackenproof.com/avalanche/avalanche-protocol).

**Comment by aaronbuchwald** [comment]
Could you please describe the API calls that are made on the node, the result, and a brief description of why you think this is unexpected behavior?

The repo that you linked to reproduce is private, so if that repo is the only way you have to reproduce the issue, a clear description of what it's doing would make a better starting place to debug.
