### ISSUE TITLE
Parallelize e2e tests

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/subnet-evm#623]
**Context and scope**
In order to speed up CI, we should be able to run all the e2e tests in parallel

**Discussion and alternatives**
 - Not sure if there's an easy way to do this with `ginkgo`. In any case, we should probably have a flag that allows for running the tests synchronously as well. 

**Open questions**
 - What's the best way to do this? Should it be with separate CI runs, or should it be done at the `ginkgo` level?
 - each create subnet assumes that it has sole access to the default funded wallet on the P-chain so we’ll need to switch to passing in a funded wallet on the P-chain so that they’re each correctly isolated

**Comment by aaronbuchwald** [comment]
Marking this as a good first issue.. I'd say this is a reasonable first issue

**Comment by richardpringle** [comment]
@aaronbuchwald, should we leave this unassigned then?
