### ISSUE TITLE
Return an Enum for Role in AllowList Contract for tests

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/subnet-evm#654]
**Context and scope**
Instead of returning a `u256`, we can return an enum which makes some compile time checks better.

**Discussion and alternatives**
do nothing?

**Open questions**
nada

**Comment by ceyonur** [comment]
Enums are internal types to Solidity. AFAIK internal enums are represented by `uint8`. Changing return type of `readAllowList` in `IAllowList` interface requires a mandatory upgrade + change to any contract using it. At most, we can use an enum in `AllowList` wrapper, but I don't think any of functions in `AllowList` contract returns `uint256`. Closing this for now. Feel free to reopen with more context.
