### ISSUE TITLE
Remove yarn dependency from example-contracts AND CI

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/subnet-evm#660]
**Context and scope**
While `yarn` *might be* better than NPM, I really don't think it makes sense to have an extra dependency. Those who prefer `yarn` will know how to do `yarn` equivalents when it comes to documentation. 

for CI, we should use the command `npm ci` which will grab all the exact dependencies that are in the package-lock.json. 

**Discussion and alternatives**
Open to alternatives, but the fewer external dependencies, the better IMO. 

**Open questions**
N/A

**Comment by richardpringle** [comment]
@ceyonur, I assigned this to you... but that doesn't mean you need to do it haha. If you don't have time or whatever, feel free to assign it back to me and I'll get to it at some point in the future.

**Comment by ceyonur** [comment]
will be closed by #672

**Comment by richardpringle** [comment]
🎉
