### ISSUE TITLE
Filter Query using FromBlock not being Honored

### ISSUE THREAD

**Issue by Abso1ut3Zer0** [ava-labs/subnet-evm#717]
**Describe the bug**
Subscribing to an event signature with a defined FromBlock in the FilterQuery is not being honored and I am being subscribed at the block head.

**To Reproduce**
Connect using a FromBlock to see if data between the FromBlock and the current block is provided.

**Expected behavior**
We should receive all data from the defined FromBlock until the block head and continue business as usual.

**Additional context**
![From_Block_Bug](https://github.com/ava-labs/subnet-evm/assets/101067738/147397c6-d6b2-4c47-a0e2-90998d6c8671)

The context around the screenshot is that the node disconnects me periodically (as expected). My subscription management code will then track which block I disconnected at, then after some time (5 seconds in this case), I will send FilterQuery's with a FromBlock set to the block at which I disconnected at. 

This is a trading application built for Dexalot, so you see order related information. There are two threads managing this. One of the threads is dealing with sending the orders while the other is subscribing to emitted events (to confirm if orders are placed, canceled, filled, etc). 

In this case you see I cancel orders which are confirmed at block 4650907 (you see logs for one thread reading before the confirmation in the thread doing the transactions). Then at block 4650909, I have two confirmed orders sent without logs from the thread reading the events (this is suspicious). Finally you see a successful resubscribe at block 4650908 (this number is coming from the actual FilterQuery I send to subscribe), before when my new orders were confirmed. I then see no data from the emitted events that are confirming those orders. This then leads to applications to go into a bad state because recovery does not seem to behave correctly since the node does not seem to honor the FromBlock setting.

**Comment by aaronbuchwald** [comment]
Thanks for reporting the issue. Could you share a code snippet with steps to reproduce if you already have this?

**Comment by Abso1ut3Zer0** [comment]
Sure, I am doing something quite simple. Here, wcm.client is simply a pointer to an ethclient.Client, and I'm using the SubscribeFilterLogs method.
![image](https://github.com/ava-labs/subnet-evm/assets/101067738/afc2d49e-3db4-468f-b616-1138ea05f5ef)
![image](https://github.com/ava-labs/subnet-evm/assets/101067738/85adfc08-0c91-4dcd-9f75-32a185d38121)

Separately, I have a component that is managing the block state such that I know at which block I disconnect (you can see the logs related to disconnecting and reconnecting in the original screenshot). This component is listening to the block head to track that state and will move the block head of my subscriptions themselves such that it sends the proper FilterQuery:

![image](https://github.com/ava-labs/subnet-evm/assets/101067738/79b95547-9fd4-4aec-bde2-c29a9c977a7c)

My manager component is the one logging showing that I did in fact send the correct FromBlock:
![image](https://github.com/ava-labs/subnet-evm/assets/101067738/ae15714b-99b2-4d6f-a37c-bbbeed2e6cc1)

I think reproducing would be simple and you can just request a historical FromBlock with ToBlock set to nil.

**Comment by aaronbuchwald** [comment]
Thanks, what version of AvalancheGo and Subnet-EVM are you running?

**Comment by Abso1ut3Zer0** [comment]
So this is an application using geth to trade on Dexalot. We are not running a node, but are communicating with Avalabs nodes operating the Dexalot Subnet. We've been noticing this the last month or two and have more recently found what is happening if that helps.

**Comment by aaronbuchwald** [comment]
Ah so you're using geth's `ethclient` to request information from the Dexalot Subnet?

Is your code public and shareable? Might be helpful to take a look at the exact logic

**Comment by Abso1ut3Zer0** [comment]
Yes, we are doing exactly that.

Unfortunately, I can't share the whole repo, but I am happy to paste anything that would be helpful. Otherwise, we can take this offline.

**Comment by darioush** [comment]
@Abso1ut3Zer0 This looks like the same issue as reported upstream here: https://github.com/ethereum/go-ethereum/issues/15063

The tldr is this is expected behavior and there are some workarounds suggested in the upstream issue.
If upstream modifies this behavior we will take the changes accordingly.
