### ISSUE TITLE
JS Tracing appears to not work as intended in subnet-evm

### ISSUE THREAD

**Issue by NickSolante** [ava-labs/subnet-evm#739]
**Describe the bug**
The JS Tracing feature should be supported and activated by the debug-tracer flag as mentioned in the Avalanche documentation: [AvalancheGo Chain Configs](https://docs.avax.network/nodes/maintain/chain-config-flags#debug-tracer). Specifically, enabling this flag in {config-dir}/chainID/config.json should allow JS Tracing functionality.
However, the problem arises when dealing with subnet-evm. Even when the debug-tracer flag is enabled in the configuration of that subnet, the JS tracing does not seem to function as expected.

**To Reproduce**
enable these configs in your subnet chain the subnet chain I was using was and will be referencing for this example will be `32sexHqc3tBQsik8h7WP5F2ruL5svqhX5opeTgXCRVX8HpbKF`
```
{
  "eth-apis":["eth","eth-filter","net","web3","internal-eth","internal-blockchain","debug","debug-tracer"]
}
```

place the config `{config-dir}/32sexHqc3tBQsik8h7WP5F2ruL5svqhX5opeTgXCRVX8HpbKF/config.json`

start the avalanchego node and do a curl request
```
curl 'http://localhost:8544/ext/bc/32sexHqc3tBQsik8h7WP5F2ruL5svqhX5opeTgXCRVX8HpbKF/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc":"2.0",
    "method":"debug_traceCall",
    "params":[
        {
            "from":null,
            "to":"0x6b175474e89094c44da98b954eedeac495271d0f",
            "data":"0x70a082310000000000000000000000006E0d01A76C3Cf4288372a29124A26D4353EE51BE"
        },
        "latest",
        {
            "tracer":"{\n    data: [],\n    fault: function (log) {},\n    step: function (log) {\n        var topicCount = (log.op.toString().match(/LOG(\\\\d)/) || [])[1];\n        if (topicCount) {\n            var res = {\n                address: log.contract.getAddress(),\n                data: log.memory.slice(parseInt(log.stack.peek(0)), parseInt(log.stack.peek(0)) + parseInt(log.stack.peek(1))),\n            };\n            for (var i = 0; i < topicCount; i++)\n                res['topic' + i.toString()] = log.stack.peek(i + 2);\n            this.data.push(res);\n        }\n    },\n    result: function () {\n        return this.data;\n    }\n}",
            "enableMemory": true,
            "enableReturnData": true,
            "disableStorage": true
        }
    ],
    "id":1
}'
```

the request should return 
`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"tracer not found"}}`

**Expected behavior**
when doing the same request I would expect no error message like the one below referenced from me targeting C chain
```
curl 'localhost:8544/ext/bc/C/rpc' \
--header 'Content-Type: application/json' \
-d '{
    "jsonrpc":"2.0",
    "method":"debug_traceCall",
    "params":[
        {
            "from":null,
            "to":"0x6b175474e89094c44da98b954eedeac495271d0f",
            "data":"0x70a082310000000000000000000000006E0d01A76C3Cf4288372a29124A26D4353EE51BE"
        },
        "latest",
        {
            "tracer":"{\n    data: [],\n    fault: function (log) {},\n    step: function (log) {\n        var topicCount = (log.op.toString().match(/LOG(\\\\d)/) || [])[1];\n        if (topicCount) {\n            var res = {\n                address: log.contract.getAddress(),\n                data: log.memory.slice(parseInt(log.stack.peek(0)), parseInt(log.stack.peek(0)) + parseInt(log.stack.peek(1))),\n            };\n            for (var i = 0; i < topicCount; i++)\n                res['topic' + i.toString()] = log.stack.peek(i + 2);\n            this.data.push(res);\n        }\n    },\n    result: function () {\n        return this.data;\n    }\n}",
            "enableMemory": true,
            "enableReturnData": true,
            "disableStorage": true
        }
    ],
    "id":1
}'
{"jsonrpc":"2.0","id":1,"result":[]}
```

**Additional context**
We're trying to run a 4337 bundler on AVAX subnets particularly the DFK subnet and this is how we found that JS tracers could possibly not be enabled or supported in the subnet-evm plugin. 

Why we need the JS tracer is that essentially we require debug_traceCall to check that incoming UserOperations are valid before accepting it into the mempool. This protects the mempool from spam and junk transactions which can lead to invalidation of other legit ops in a batch. However debug_traceCall with the default tracers is not enough. This validation is quite complex because we need to check everything from opcodes used and storage accessed during certain phases of the userOp lifecycle. To do this we need to send custom JS code along with the debug_traceCall. This tells the execution client to trace the call given a specific custom tracer. This is a critical part to bundler security and compliance to the spec

**Comment by hazim-j** [comment]
Thanks for the confirmation @aaronbuchwald. Looking forward to the next release 🫡

**Comment by NickSolante** [comment]
@aaronbuchwald do we possibly know when the release is coming? 👀

**Comment by aaronbuchwald** [comment]
Closing since this PR has been merged. Planning to do the release on Monday.
