### ISSUE TITLE
Load Simulator: Add Metrics for Client Facing Tx Latency

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#741]
The load simulator should track the latency from issuing a transaction to the network to the time of confirmation. This metric should provide an accurate measurement of the latency experienced by users from the time that they issue a transaction to the network to the point where they can confirm it as finalized.

The current load simulator uses a generic worker that issues and confirms transactions, so we can add tracking for issuance/confirmation times directly into the agent by:

1. Adding the transaction hash and issuance time to a map when it's first issued: https://github.com/ava-labs/subnet-evm/blob/v0.5.2/cmd/simulator/txs/agent.go#L73
2. Removing the transaction hash and issuance time from the map when it's confirmed and adding the relevant metric to a prometheus histogram or summary: https://prometheus.io/docs/practices/histograms/

The agent / caller of the agent should be responsible for ensuring that it does not issue too many pending and unconfirmed transactions to the point of causing an OOM. In other words, it should be the agent's responsibility to meter the number of unconfirmed transactions so that this map does not get too big.

**Comment by anusha-ctrl** [comment]
So currently we have a Prometheus server where we expose summary quantile metrics of individual issuance and confirmation tx times. Issuance -> Confirmation times are just issuance + confirmation times summed together.  I'm not sure we need the map approach

**Comment by aaronbuchwald** [comment]
Hmmm we want confirmation time for a transaction be the time from issuing the transaction to confirming it. If we don't have a record of when the transaction was issued when we go to confirm it, we won't get an accurate metric (added a comment to the current PR here: https://github.com/ava-labs/subnet-evm/pull/706/files#r1268777869).

**Comment by anusha-ctrl** [comment]
So the agent only deals in generic types therefore we can't access any attributes of the tx including the tx hash. If we were to do this we should do it in the worker.

**Comment by aaronbuchwald** [comment]
We can add a constraint on the generic type so that it can return a `common.Hash` or `ids.ID` type
