### ISSUE TITLE
0.5.3 release

### ISSUE THREAD

**Issue by aphexmunky** [ava-labs/subnet-evm#763]
Could you create a github release for 0.5.3 please. I'm playing around with [gogotools](https://github.com/multisig-labs/GoGoTools) and it brings in binary versions via the github releases

**Comment by aaronbuchwald** [comment]
Interesting. What did you see when playing with gogotools? We just put out the v0.5.3 release this morning. This is published via goreleaser [here](https://github.com/ava-labs/subnet-evm/blob/master/.github/workflows/release.yml#L40), so it should have published it as the latest release at the same time as publishing the binaries.

**Comment by aaronbuchwald** [comment]
Awesome, thanks for creating the issue to track!
