### ISSUE TITLE
Warp E2E Test Flake during Network Setup: IssueAddPermissionlessValidatorTx not committed

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#848]
**Describe the bug**
During the setup of two subnets for the warp e2e test, the P-Chain wallet hits an error adding a permissionless validator tx
![Screenshot 2023-09-12 at 10 26 16](https://github.com/ava-labs/subnet-evm/assets/24684335/84de8769-f687-44f4-8877-13281a979898)

https://github.com/ava-labs/subnet-evm/actions/runs/6160584662/job/16717885928?pr=823#step:10:2196

**Comment by ceyonur** [comment]
I think we haven't seen this for a while. We can reopen if we see this again.
