### ISSUE TITLE
Remove DUpgrade Specific Tests from Precompile Template after DUpgrade Activation

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#851]
After the DUpgrade activates, any newly generated precompiles with the precompile template can assume that the DUpgrade has already been activated on production networks.

At that point, we should switch to remove any unnecessary specific DUpgrade values from the template generated tests.

**Comment by ceyonur** [comment]
I've checked and could not see any specific test that can be removed now. Put up a PR to remove confusing comment (that might lead ppl to feel safe to change the parameter)
