### ISSUE TITLE
PredicateResults: Use tx offset instead of tx hash in map

### ISSUE THREAD

**Issue by dhrubabasu** [ava-labs/subnet-evm#898]
https://github.com/ava-labs/subnet-evm/blob/master/precompile/results/predicate_results.go#L43-L45

```golang
type PredicateResults struct {
	Results map[common.Hash]TxPredicateResults `serialize:"true"`
}
```

Instead of using `common.Hash` as the key, we should be able to use a `uint32` (or a `uint16` depending on the maximum number of txs allowed in a block)

**Comment by nytzuga** [comment]
@dhrubabasu is the idea to use the transaction position in a given block instead of the transaction hash?

**Comment by dhrubabasu** [comment]
Yes, that's the idea
