### ISSUE TITLE
Do not attempt to parse predicate results if not verified

### ISSUE THREAD

**Issue by ceyonur** [ava-labs/subnet-evm#904]
In there we parse bytes to put in the returned error (mostly for debugging purposes): https://github.com/ava-labs/subnet-evm/blob/master/plugin/evm/block.go#L296-L302

However this leads to an additional overhead + it's most likely not be parse-able at all so we can skip parsing it and return bytes as they're.

**Comment by darioush** [comment]
We need to parse the bytes here (not only to create the error message), but to ensure this code has no possibility to error:
https://github.com/ava-labs/subnet-evm/blob/master/core/evm.go#L62-L65

I explored adding err return value here: https://github.com/ava-labs/subnet-evm/pull/896 but I don't like that code. Perhaps you are suggesting the alternative path where we could expect the caller to parse bytes and pass in the parsed result?

**Comment by ceyonur** [comment]
> We need to parse the bytes here (not only to create the error message), but to ensure this code has no possibility to error:
> 
> https://github.com/ava-labs/subnet-evm/blob/master/core/evm.go#L62-L65
> 
> 
> 
> I explored adding err return value here: https://github.com/ava-labs/subnet-evm/pull/896 but I don't like that code (seems would introduce further maintenance burden when merging from upstream). Perhaps you are suggesting the alternative path where we could expect the caller to parse bytes and pass in the parsed result?

I think if bytes are not equal we can immediatly return the error without parsing. Then we can add another check if its parsable but I doubt that is actually needed.  it will be same bytes with the predicate we constructed and encoded and thus guaranteed to be parsable(unless there is a problem in the codec itself).
