### ISSUE TITLE
Some links on the README page are dead. The relevant text is in the description area.

### ISSUE THREAD

**Issue by irfanevrens** [ava-labs/subnet-evm#910]
The Subnet EVM is compatible with almost all Ethereum tooling, including [Remix](https://docs.avax.network/dapps/smart-contracts/deploy-a-smart-contract-on-avalanche-using-remix-and-metamask/), [Metamask](https://docs.avax.network/dapps/smart-contracts/deploy-a-smart-contract-on-avalanche-using-remix-and-metamask/) and [Truffle](https://docs.avax.network/dapps/smart-contracts/using-truffle-with-the-avalanche-c-chain/).

**Comment by ceyonur** [comment]
Seems we have move some doc pages. CC'ing dev-rel team.
@ava-labs/developer-relations

**Comment by ceyonur** [comment]
This should be fixed with https://github.com/ava-labs/subnet-evm/pull/926. Feel free to reopen/create issue if you think there's more. 

Thanks for reporting!
