### ISSUE TITLE
`trace` module / `debug_traceTransaction` RPC method?

### ISSUE THREAD

**Issue by lukeramsden** [ava-labs/subnet-evm#92]
Does the subnet-evm implementation contain any functionality for tracing transactions / checking state diff of transactions? This is very useful functionality when e.g. running an archive node for a chain. I see there's a `TraceTransaction` function in `eth/tracers/api.go`, but I can't see how this is exposed over RPC? I have enabled the `debug-tracer` in config.

**Comment by lukeramsden** [comment]
Hmm, this seems to be an issue with my setup causing the subnet config not actually picking up my custom config - I'll investigate further. Sorry for the noise.

**Comment by thomasnft** [comment]
Hi,
I have enable the `debug` and `debug-tracer` modules in `eth-apis` fields, but encountered this error on calling `debug_traceTransaction`.
My request:
```
curl --request POST \
     --url http://localhost:9664/ext/bc/tVPqVu1aX1V2xSo3mpp1KnhftrS65E8CSgVdq5bYN2dpPKRcK/rpc \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "debug_traceTransaction",
  "params": [
    "0x110eb58b69efd5c5a0953c9a1dcee48d464c8f53ca3bc5f8aaa5007c03598267",
    {
      "tracer": "callTracer"
    }
  ]
}
'
```

Error response:
`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"required historical state unavailable (reexec=0)"}}`

Anyone know how to fix that?

**Comment by thomasnft** [comment]
For anyone who encountered the same issue, the solution to fix it is set the `pruning-enabled` field in config.json to `false` value. By default, it is set to `true`, which means the AvalancheGo node will prune historical database, thus disabling the `debug_traceTransaction` api.
Here is my chain config.json file:
`{
  "eth-apis": ["eth", "eth-filter", "net", "web3", "internal-eth", "internal-blockchain",  "internal-transaction", "internal-account", "debug", "debug-tracer"],
  "pruning-enabled": false
}`
