### ISSUE TITLE
[wip] Shared memory precompile: moving assets created on C-Chain to P-Chain

### ISSUE THREAD

**Issue by darioush** [ava-labs/subnet-evm#938]
## Context and scope
A common ask among subnet users is the ability to perform subnet staking with assets created (or accessible) on the C-Chain. This simplifies the use of existing liquidity for subnet staking. Avalanche's C & P chain can communicate & exchange tokens using the "shared memory", a database present on all nodes running both chains.

Avalanche's C-Chain supports [import](https://github.com/ava-labs/coreth/blob/12f262c5e361c73d4fd631f33107d297bc19045d/plugin/evm/import_tx.go) & [export](https://github.com/ava-labs/coreth/blob/12f262c5e361c73d4fd631f33107d297bc19045d/plugin/evm/export_tx.go) transactions that allow transfer of AVAX and ANT assets (Avalanche native token) between the two chains. However:
- These transactions can only be issued by EOAs and are Avalanche specific transactions (as opposed to EVM transactions).
- In the [Apricot Phase 6 network upgrade](https://medium.com/avalancheavax/apricot-phase-6-native-asset-call-deprecation-a7b7a77b850a), smart contract access to ANT balances was [deprecated](https://github.com/ava-labs/coreth/blob/37c9cc40b2bc8a4bc72906c4091a8839a888d4f7/core/vm/contracts.go#L158-L160). 
 
This issue describes a precompile that enables smart contracts to import / export AVAX and custom assets, with the main use case of enabling staking custom tokens for subnets on the P chain. Other use cases are not considered primary, but may be supported.

***Important***: This specification is a draft and *all* parts of it are subject to change.

### Solidity interface
Similar to coreth's export and import functionality, the shared memory precompile handles translating the EVM's account based model to and from the shared memory's UTXO model (eg, for use on the P-Chain).

It provides the ability for contracts to import & export either a UTXO, or AVAX to another chain within the same subnet. To do this, we will expose the following interface for a new precompile:

```sol
function getNativeTokenAssetID(address caller) external view returns (bytes32 assetID);
function exportUTXO(uint64 amount, bytes32 destinationChainID, uint64 locktime, uint64 threshold, address[] calldata addrs) external;
function exportAVAX(uint256 amount, bytes32 destinationChainID, uint64 locktime, uint64 threshold, address[] calldata addrs) external payable;
function importUTXO(bytes32 sourceChain, bytes32 utxoID) external returns (uint64 amount, bytes32 assetID, uint64 locktime, uint64 threshold, address[] calldata addrs);
function importAVAX(bytes32 sourceChain, bytes32 utxoID) external;
```

- `getNativeTokenAssetID` returns the assetID of the native token for the caller.  This is used to determine the assetID of the UTXO that is exported, and is computed as `sha256(caller, sourceChainID)`. Note `sourceChainID` corresponds to the Avalanche blockchain ID not the EVM chainID.

- `exportUTXO` will allow a contract to export a UTXO with an assetID derived from the contract address. The UTXO will be placed into shared memory when the block is accepted.

- `exportAVAX` will allow a contract to export a UTXO containing AVAX from the contract address. This will require a balance check internal to the EVM and will place a UTXO into shared memory containing AVAX on accept.

- `importUTXO` will be used to acknowledge, process, and remove a UTXO from shared memory. The contract calling this precompile will be responsible for processing the details of the UTXO and crediting the owner of the UTXO with the funds held by the UTXO. The UTXO will be removed from shared memory when the block is accepted.

- `importAVAX` will allow a contract to import a UTXO with AVAX as the assetID. It will verify the caller address is the sole owner of the UTXO and then increment the AVAX balance for the caller. The UTXO will be removed from shared memory when the block is accepted.

Under the hood, each of the import/export functions causes a log (event) to be emitted that affects the shared memory when the block corresponding to the transaction is [accepted](https://github.com/ava-labs/subnet-evm/pull/537/files#diff-9a870b1572ea65697aea0a8f959e0ee20efa4ff3370c3e39dcc2f3ec436b4fc3R127). Details of the events can be found here: [ISharedMemory.sol](https://github.com/ava-labs/subnet-evm/pull/537/files#diff-29d2356f7fbbc5aeda1bde5c8c8536a0b715a294285ee062613f7be22900006c)

For the most up-to-date developments, you can follow the work-in-progress [PR](https://github.com/ava-labs/subnet-evm/pull/537/). Note that while we are targeting the C-Chain (coreth) for the main use case, implementation is progressing on the subnet-evm repository. This helps keep the work as generic as possible and is inline with other precompile development.

**Important**: Draft PRs are subject to change and are not ready for consideration to be merged without significant changes.

### Precompile's storage trie

The precompile tracks each of the modifications it makes to the shared memory as part of state.
This allows the node to apply changes to the shared memory after state sync.

Additionally, the precompile tracks the UTXOs that are imported by contracts. This allows the precompile to prevent double spend of UTXOs that are imported in processing blocks.

Modifications to the statedb may be needed to support the storage of variable length data (i.e, the UTXO specification). Ideas such as those specified [here](https://docs.soliditylang.org/en/v0.8.21/internals/layout_in_storage.html#mappings-and-dynamic-arrays) may be used for a more standard approach that complies with existing tooling.

### Use of the shared memory precompile with multi-sig

When using `exportUTXO` or `exportAVAX`, the caller (e.g., a token wrapper smart contract) can specify an output UTXO with multiple addresses as owners and a threshold. This allows the caller to create a multi-sig UTXO in the shared memory and import & use it on the P-Chain (e.g., for staking).

When using `importUTXO` or `importAVAX`, the exporting chain has already verified the signatures and threshold before exporting. However, additional care is needed at the precompile level to ensure the UTXO is not imported by a different contract:

An import is allowed if the UTXO's spender matches the caller's address, the timelock is passed, and the threshold is 1.

### Specifying the UTXO to import

Import transactions need to specify the UTXO that is being imported. This is implemented by specifying the UTXO details [encoded](https://github.com/ava-labs/subnet-evm/pull/537/files#diff-bad31c79a29f25209b83e08f0cb6e354f701c9278fe414c261be95c4f486d759R24) in the transaction's [access list](https://eips.ethereum.org/EIPS/eip-2930), with the address of the shared memory precompile as the address and the UTXO details encoded in the storage slots.

The UTXO must be present in shared memory for the node to consider the transaction to be valid when it is processing blocks in consensus with the network.  Nodes that are bootstrapping rely on prior network consensus to ensure the UTXOs named in import transactions were valid.

### Deprecation of import & export transactions

After the precompile is implemented (and sufficient grace period), we may consider deprecating the existing import & export transactions. This will simplify the codebase and reduce the number of transaction types that need to be supported, and provide a more EVM native way of interacting with the shared memory.
Additionally, the atomic trie may be deprecated or merged with the storage of this precompile.

## Open questions
- Support importing multiple UTXOs in a single transaction
- Support a single contract exporting multiple tokens (i.e, with an index)
- Should we support the ability for importAVAX to import to an address other than the caller?
- Allowing contracts to import UTXOs that are not their own (i.e, a contract can import a UTXO created by another contract)? Note this does not allow exporting UTXOs that are not the caller's.
- Exact storage layout of the precompile's storage trie
- Handling transactions that name invalid UTXOs in the access list

**Comment by ceyonur** [comment]
This will superseded by ACP-77
