### ISSUE TITLE
Auto-Generated Code Checker is flaky

### ISSUE THREAD

**Issue by ceyonur** [ava-labs/subnet-evm#972]
Seems that this test flakes:
https://github.com/ava-labs/subnet-evm/actions/runs/6656316075/job/18088570960

**Comment by StephenButtolph** [comment]
see: https://github.com/ava-labs/avalanchego/pull/2184 for how we addressed this in avalanchego

**Comment by ceyonur** [comment]
> see: [ava-labs/avalanchego#2184](https://github.com/ava-labs/avalanchego/pull/2184) for how we addressed this in avalanchego

Thanks 🙌  , I ported it here https://github.com/ava-labs/subnet-evm/pull/974/files
